name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    name: Build and Push Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Initialize Go module
        run: |
          go mod init CloudNomster/discord-gpt4o-bot

      - name: Download Go dependencies
        run: |
          go mod tidy

      - name: Build Go project
        run: |
          go build -o bot .

      - name: Build Docker image
        run: |
          docker build -t bot-test:latest .

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_HOST }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.HARBOR_HOST }}/library/bot-test:latest

      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Job ${{ job.status }}"}' https://discord.com/api/webhooks/${{ secrets.DISCORD_ID }}/${{ secrets.DISCORD_TOKEN }}
